
spring:
  data:
    redis:
      host: localhost
      port: 6379

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static:
    s3:
      bucket:

jasypt:
  encryptor:
    password:
